export const AUTOMATION_CONNECT_TIMEOUT_MS = 10_000;
export const AUTOMATION_ACTION_TIMEOUT_MS = 8_000;
export const AUTOMATION_NAVIGATION_TIMEOUT_MS = 20_000;
export const MAX_AUTOMATION_SELECTOR_LENGTH = 500;
export const MAX_AUTOMATION_TEXT = 20_000;
export const MAX_AUTOMATION_ARIA = 12_000;
export const MAX_AUTOMATION_ELEMENTS = 120;
export const AGENT_REF_ATTRIBUTE = "data-radar-agent-ref";
