export type { RadarApi } from "../shared/radar-api";

export type {
  AiAuditEntry,
  AiContextPreview,
  AiProviderId,
  AiRunRequest,
  AiRunResult,
  AiSettings,
  AiTaskOutput,
  AiTaskType,
  AiBrowserHelperOutput,
  AiCaptureSummaryOutput,
  AiRepeaterDraftItem,
  AiRepeaterDraftsOutput,
  AiReportNotesOutput,
  AiScopeChecklistOutput
} from "./ai/types";

export type {
  AutomateCluster,
  AutomateExtract,
  AutomateLimits,
  AutomatePayloadLocation,
  AutomatePayloadPosition,
  AutomatePayloadSet,
  AutomatePayloadSetSource,
  AutomateResult,
  AutomateResultMarker,
  AutomateRule,
  AutomateRuleKind,
  AutomateRuleTarget,
  AutomateRunStatus,
  AutomateSession,
  BrowserState,
  BurstResult,
  CapturedRequest,
  CaptureInterceptRecord,
  EvidenceAnnotation,
  Finding,
  FindingConfidence,
  FindingEvidenceKind,
  FindingEvidenceRef,
  FindingReport,
  FindingReportOptions,
  FindingSeverity,
  FindingStatus,
  FindingTemplateId,
  InstalledPlugin,
  WorkflowDefinition,
  WorkflowInput,
  WorkflowMode,
  WorkflowResult,
  WorkflowResultLevel,
  WorkflowRun,
  WorkflowRunSource,
  WorkflowRunStatus,
  WorkflowScopePolicy,
  WorkflowStep,
  WorkflowStepKind,
  PluginInstallPreview,
  PluginInstallStatus,
  PluginManifest,
  PluginManifestPanel,
  PluginPermission,
  InterceptConfig,
  InterceptQueueItem,
  InterceptResponseDraft,
  InterceptResolution,
  InterceptRule,
  InterceptStage,
  InterceptState,
  LocalContext,
  LocalProfile,
  LocalSession,
  LocalSessionSummary,
  LocalWorkspace,
  MatchReplaceHit,
  MatchReplaceRule,
  MatchReplaceStage,
  MatchReplaceTarget,
  ProjectNote,
  ProxyProfile,
  ProxyProfileId,
  ProxyState,
  ReplayCollection,
  ReplayDraft,
  ReplayEnvironment,
  ReplayHistoryEntry,
  ReplayResult,
  ReplayTab,
  ReplayTabState,
  SavedFilter,
  SavedView,
  SavedViewTarget,
  SslEvent,
  TlsDetails,
  WebSocketDirection,
  WebSocketEvent,
  WebSocketReplayDraft,
  WebSocketReplayResult
} from "../shared/domain";

export type {
  AdvancedTestingSummary,
  ApiImportDraft,
  ApiImportResult,
  AuthMatrixRow,
  GraphQlOperation,
  GraphQlReview,
  HeaderBehaviorSignal,
  ParameterFinding,
  ProxyGuidance,
  SecretDetection
} from "../shared/advancedTesting";

export type {
  AgentFinding,
  AgentPolicy,
  AgentRunMemoryEntry,
  AgentRunProfileId,
  AgentRun,
  AgentRunRequest,
  AgentRunStatus,
  AgentTimelineEntry,
  AppMode
} from "../shared/agent-types";
export type { AgentRunProfile } from "../shared/agentProfiles";

export type {
  GlobalSearchKind,
  GlobalSearchMatch,
  GlobalSearchRequest,
  GlobalSearchResponse,
  GlobalSearchResult,
  GlobalSearchTarget,
  GlobalSearchTargetView
} from "../shared/globalSearch";

export type {
  ProjectBundle,
  ProjectBundleApplyResult,
  ProjectBundleExportPreview,
  ProjectBundleImportPreview,
  ProjectBundleOptions,
  ProjectBundleRedactionProfile
} from "../shared/projectBundle";

export type { HandoffPackageOptions, HandoffPackagePreview } from "../shared/handoffPackage";
